import type { ChatSession } from '@/store/chat-store';

/**
 * Export chat history to PDF using browser's print functionality
 * Opens a new window with print-friendly HTML that can be saved as PDF
 */
export function exportChatToPDF(session: ChatSession) {
  const { title, messages, createdAt } = session;

  // Format messages as HTML
  const messagesHtml = messages.map((msg) => {
    const isUser = msg.role === 'user';
    const timestamp = new Date(msg.timestamp).toLocaleString();

    // Format sources if present
    let sourcesHtml = '';
    if (msg.sources && msg.sources.length > 0) {
      sourcesHtml = `
        <div class="sources">
          <div class="sources-header">Sources:</div>
          <ul>
            ${msg.sources.map(s => `
              <li>
                <strong>${escapeHtml(s.title)}</strong>
                ${s.relevance ? ` (${Math.round(s.relevance * 100)}% match)` : ''}
                <span class="category">${escapeHtml(s.category)}</span>
              </li>
            `).join('')}
          </ul>
        </div>
      `;
    }

    return `
      <div class="message ${isUser ? 'user' : 'assistant'}">
        <div class="message-header">
          <span class="role">${isUser ? 'You' : 'Archevi'}</span>
          <span class="timestamp">${timestamp}</span>
        </div>
        <div class="message-content">${escapeHtml(msg.content)}</div>
        ${sourcesHtml}
      </div>
    `;
  }).join('');

  // Create the full HTML document
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(title)} - Archevi Chat Export</title>
  <style>
    * {
      box-sizing: border-box;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      color: #1a1a1a;
      line-height: 1.6;
    }
    .header {
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      margin: 0 0 8px 0;
      font-size: 24px;
      color: #111827;
    }
    .header .meta {
      color: #6b7280;
      font-size: 14px;
    }
    .header .brand {
      display: flex;
      align-items: center;
      gap: 8px;
      margin-bottom: 16px;
      color: #7c3aed;
      font-weight: 600;
    }
    .message {
      margin-bottom: 24px;
      page-break-inside: avoid;
    }
    .message.user {
      background: #f3f4f6;
      border-radius: 12px;
      padding: 16px;
    }
    .message.assistant {
      background: #faf5ff;
      border-radius: 12px;
      padding: 16px;
      border-left: 4px solid #7c3aed;
    }
    .message-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 8px;
      font-size: 13px;
    }
    .role {
      font-weight: 600;
      color: #374151;
    }
    .message.assistant .role {
      color: #7c3aed;
    }
    .timestamp {
      color: #9ca3af;
    }
    .message-content {
      white-space: pre-wrap;
      word-wrap: break-word;
    }
    .sources {
      margin-top: 16px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
      font-size: 13px;
    }
    .sources-header {
      font-weight: 600;
      color: #6b7280;
      margin-bottom: 8px;
    }
    .sources ul {
      margin: 0;
      padding-left: 20px;
    }
    .sources li {
      margin-bottom: 8px;
    }
    .category {
      display: inline-block;
      margin-left: 8px;
      padding: 2px 8px;
      background: #f3f4f6;
      border-radius: 4px;
      font-size: 11px;
      color: #6b7280;
      text-transform: capitalize;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      color: #9ca3af;
      font-size: 12px;
    }
    @media print {
      body {
        padding: 0;
      }
      .message {
        break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M21 8v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8"/>
        <path d="M21 8l-9 6-9-6"/>
        <path d="M3 8l9-6 9 6"/>
      </svg>
      Archevi
    </div>
    <h1>${escapeHtml(title)}</h1>
    <div class="meta">
      Conversation started: ${new Date(createdAt).toLocaleString()}<br>
      Exported: ${new Date().toLocaleString()}<br>
      ${messages.length} messages
    </div>
  </div>

  <div class="messages">
    ${messagesHtml}
  </div>

  <div class="footer">
    Generated by Archevi - Family Document Intelligence
  </div>
</body>
</html>
  `;

  // Open in new window and trigger print
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();

    // Wait for content to load, then trigger print
    printWindow.onload = () => {
      printWindow.print();
    };

    // Fallback for browsers that don't fire onload
    setTimeout(() => {
      printWindow.print();
    }, 500);
  }
}

/**
 * Escape HTML special characters to prevent XSS
 */
function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}
